services:
  postgres:
    image: postgres:14-alpine
    container_name: finance_etl_db
    environment:
      POSTGRES_DB: finance_etl
      POSTGRES_USER: andresbrocco
      POSTGRES_PASSWORD: senhaforte
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
